# Generated by Django 3.0.7 on 2020-06-28 02:19

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Form', '0004_auto_20200628_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
